Remove constant function call for VCS
pulp-platform/axi pull request #208
Opened 2022-02-18 02:08 UTC by bluewww

This basically reverts d24303f0df9d33b8b0ff4e4b2f486ec25d2cf1a8 for vcs.
The simulator cannot deal with constant function calls where the
argument comes from a struct through a parameter port.

This is currently a rather ugly hack that should serve as a basis for a discussion.

2022-02-18 10:21 UTC, accuminium requested changes
Thanks for your efforts to debug this and propose a first solution, @bluewww!

I agree that we need to make a reasonable effort for finding workarounds to VCS limitations, and that might introduce more `ifdef`s. However, as `cf_math_pkg::idx_width()` is not equivalent to `$clog2()` when the argument has value `1`, additional work is required to solve those cases. One option could be to introduce a VCS-only dependent parameter:
```sv
`ifdef VCS
parameter int unsigned MstPortsIdxWidth = Cfg.NoMstPorts == 32'd1 ? 32'd1 : unsigned'($clog2(Cfg.NoMstPorts))
`endif
```

2022-02-18 11:34 UTC, bluewww commented
I caught this problem by issuing an elaboration time error see https://github.com/pulp-platform/axi/pull/208/commits/59b2f88e4fad0aea9aa72a4425497160431427b7#diff-e525faff2463489e38729f200de6530d6911b2d11b58fc46928d1e1e884683c9R56-R60

2022-02-19 09:09 UTC, bluewww commented
I rebased and dropped the fixes which you address in this PR https://github.com/pulp-platform/axi/pull/210

As you suggested I now introduce vcs dependent parameters. This works too and for all cases of `Cfg.NoMstPorts >=1` to work

The placement of the commas is quite unsatisfying maybe you have a better idea.

2022-02-19 16:21 UTC, accuminium requested changes

2022-02-19 16:21 UTC, accuminium commented on src/axi_xbar.sv
> +  , localparam int unsigned MstPortsIdxWidthOne = Cfg.NoMstPorts == 32'd1 ? 32'd1 : unsigned'($clog2(Cfg.NoMstPorts + 1))
This `localparam` is not used in the port list, so please move it into the module body (e.g., just before line 61).

2022-02-21 14:03 UTC, accuminium approved these changes
LGTM, thanks!

2022-02-21 15:07 UTC, merged