axi_sim_mem: Add the possibility to emit read and write errors
pulp-platform/axi pull request #242
Opened 2022-08-04 08:33 UTC by thommythomaso

2022-08-04 11:51 UTC, andreaskurth requested changes

2022-08-04 11:51 UTC, andreaskurth commented on src/axi_sim_mem.sv
> +  axi_pkg::resp_t werr[addr_t] = '{default: axi_pkg::BURST_FIXED};
Shouldn't these be `axi_pkg::RESP_OKAY`?

2022-08-04 11:51 UTC, andreaskurth commented on src/axi_sim_mem.sv
> +                error_happened = error_happened | werr[byte_addr];
Suppose one byte has `RESP_EXOKAY` and the next byte has `RESP_SLVERR`. Then this OR would result in `RESP_DECERR`, right? That seems wrong to me.

2022-08-08 06:38 UTC, thommythomaso commented on src/axi_sim_mem.sv
> +  axi_pkg::resp_t werr[addr_t] = '{default: axi_pkg::BURST_FIXED};
Yes of course. Sorry for that.

2022-08-08 06:42 UTC, thommythomaso commented on src/axi_sim_mem.sv
> +                error_happened = error_happened | werr[byte_addr];
For writes, we only get one answer once the entire burst is completed. We decided here that if one byte of a write burst throws an error, the entire burst will be completed with a b answer carrying said error.

2022-08-15 20:24 UTC, micprog commented on src/axi_sim_mem.sv
> +                error_happened = error_happened | werr[byte_addr];
@thommythomaso I believe the concern here is that `RESP_EXOKAY = 01` while `RESP_SLVERR = 10` which through OR would equate to `RESP_DECERR = 11`, which I agree is not what the response should be. Overall I'd argue as this module does not support ATOPs or locking, all responses should be either `RESP_OKAY = 00` or `RESP_SLVERR = 10` (and maybe `RESP_DECERR`), as `RESP_EXOKAY` does not make sense.
Additionally, following the specification:

> A7.2.5 on responses to exclusive access: An exclusive read has one or more response beats. These can be a mixture of EXOKAY, SLVERR and DECERR or a mixture of OKAY, SLVERR and DECERR. Mixing EXOKAY and OKAY responses in the same transaction is not permitted.
> B1.3.1 on conversion rules: Where a wide transaction is converted to multiple narrower transactions, the component responsible for the conversion must combine the responses to all of the narrower transactions, to produce a single response for the original transaction. Any error response is sticky. If both a SLVERR and a DECERR are received then the first response received is used for the combined response.

I would therefore argue that this module may need to limit possible responses to only `RESP_OKAY` and `RESP_SLVERR`, possibly also `RESP_DECERR` if needed.

Does something like this make sense for you? Something similar is also needed for the `rerr`.
```suggestion
                error_happened = (error_happened != axi_pkg::RESP_OKAY) ? error_happened : ((werr[byte_addr] == axi_pkg::RESP_EXOKAY) ? axi_pkg::RESP_OKAY : werr[byte_addr]);

```

2022-08-16 07:27 UTC, thommythomaso commented on src/axi_sim_mem.sv
> +                error_happened = error_happened | werr[byte_addr];
I get this point. However, errors have to be deliberately introduced into the error arrays by the user (it's not possible to inject them from the AXI bus) so from my point of view, a mix between `SLVERR` and `EXOKAY` should be counted as a user error. 
I agree that is better to be resilient against such user errors so this line should be changed. Should https://github.com/pulp-platform/axi/blob/db457aa8d8996d87ca72486a9b15873042e04d38/src/axi_pkg.sv#L264-L291 be used to merge the responses here?

2022-08-16 07:32 UTC, micprog commented on src/axi_sim_mem.sv
> +                error_happened = error_happened | werr[byte_addr];
`resp_precedence` looks good to me, I was unaware of this feature.

2022-08-16 07:35 UTC, thommythomaso commented on src/axi_sim_mem.sv
> +                error_happened = error_happened | werr[byte_addr];
I will rewrite the response accumulation using `resp_precedence`.

2022-08-16 08:57 UTC, micprog approved these changes
LGTM, thanks for the fix

2022-08-23 06:27 UTC, andreaskurth approved these changes
Thanks for the discussion and implementing the feedback!

2022-08-24 07:53 UTC, merged