FuseSoC and XSIM
pulp-platform/axi pull request #262
Opened 2022-09-15 11:58 UTC by micprog

Improves compatibility for fusesoc and vivado xsim and includes a limited test for this in the internal CI. Replaces #232. Fixes #226, #247.

2022-09-15 12:00 UTC, thommythomaso commented on .gitlab-ci.yml
> +    - vitis $HOME/.local/bin/fusesoc run --tool xsim --target sim --no-export pulp-platform.org::axi:$(cat ../VERSION | sed s/-/./g)
we should add a version here and use the newest one installed (`vitis-2022.1-zr`)

2022-09-15 12:01 UTC, thommythomaso commented on CHANGELOG.md
>  ### Added
Mention vitis and fusesoc CI maybe?

2022-09-15 12:02 UTC, thommythomaso approved these changes
LGTM!

2022-09-27 16:29 UTC, skokvermon requested changes
XSIM is not defined in vivado 2022
XILINX_SIMULATOR is predefined
https://docs.xilinx.com/r/en-US/ug900-vivado-logic-simulation/Predefined-Macros

2022-09-27 16:50 UTC, skokvermon commented
depends on https://github.com/pulp-platform/common_cells/pull/139

2022-09-27 17:34 UTC, merged

2022-09-27 17:42 UTC, thommythomaso commented
Which version of XSIM do you use?

2022-09-27 17:47 UTC, thommythomaso commented
We use Vivado 2022.04 in the CI, which works just fine for us.

2022-09-27 18:22 UTC, thommythomaso commented
> I have vivado 2022.1 CI use `sim` target which works. Most other bench targets will show the randomize error message Unfortunately, if you correct it, you will mostly have unsupported `default disable iff` Then if corrected, I had seg fault on axi_xbar bench which I can't find any workaround.
> 
> I found out that I could workaround one of these segfaults in my own bench by replacing
> 
> ```
>       axi_drv_t::ax_beat_t ax_beat = new();
> ```
> 
> by
> 
> ```
>       axi_test::axi_driver #(.AW(AXI_AW), .DW(AXI_DW), .IW(AXI_IW), .UW(AXI_UW))::ax_beat_t ax_beat = new();
> ```
> 
> It doesn't like using a subtype of a typedef type. However, I can't make axi_xbar bench to work

I just tried it locally as well and it fails with the `sim_xbar` target. I will revert the define ofc. Sorry for that.

Can you maybe create a new PR with all the fixes you require for the xbar TB to work?

2022-09-27 19:02 UTC, skokvermon commented
https://github.com/pulp-platform/axi/pull/264