axi_dw_downsizer: initialize the write response buffer with EXOKAY
pulp-platform/axi pull request #281
Opened 2023-01-18 17:56 UTC by cfuguet

This modification allows to correctly forward the response status of multi-beat exclusive write operations.

This RESP_EXOKAY response code has the lowest priority when merging the response code from a multi-beat write response.

2023-03-28 17:01 UTC, cfuguet commented
Yes, you are right. I can do the modifications for AR and R channels, too.

I will do that and push as soon as possible.

Thanks for the review

2023-03-29 13:30 UTC, cfuguet commented
Hello, I did the changes.

Regards,

2023-03-30 13:35 UTC, SamuelRiedel requested changes

2023-03-30 13:35 UTC, SamuelRiedel commented on src/axi_dw_downsizer.sv
> +              r_req_d.burst_resp   = axi_pkg::RESP_EXOKAY;
Thanks. :) However, this member does not exist in this struct. I think you have to set the default value here: https://github.com/pulp-platform/axi/blob/master/src/axi_dw_downsizer.sv#L383 with `r_req_d.r.resp = axi_pkg::RESP_EXOKAY;`

2023-03-30 13:35 UTC, SamuelRiedel commented on src/axi_dw_downsizer.sv
> +          r_req_d.burst_resp   = axi_pkg::RESP_EXOKAY ;
Same here.

2023-04-02 10:32 UTC, SamuelRiedel approved these changes
Thanks :+1: The internal CI also passes, so this looks good to me.

2023-05-08 07:21 UTC, merged