Minor improvements to `axi_rand_master`
pulp-platform/axi pull request #329
Opened 2024-01-16 15:27 UTC by luca-valente

2024-02-28 18:54 UTC, micprog requested changes
LGTM, if possible I would prefer to not change the interface though.

2024-02-28 18:54 UTC, micprog commented on src/axi_test.sv
> +    function void add_traffic_shaping(input int unsigned len, input int unsigned size, input int unsigned freq);
This changes the interface making a non-breaking release difficult. @luca-valente do you think you can use a separate function (e.g. called `add_traffic_shaping_sized`) to add this functionality, and keeping the old function the same but wrapping this new one?

2024-02-29 13:36 UTC, luca-valente commented on src/axi_test.sv
> +    function void add_traffic_shaping(input int unsigned len, input int unsigned size, input int unsigned freq);
Sure! I can do that :smile: thanks for the feedback

2024-03-20 14:17 UTC, luca-valente commented on src/axi_test.sv
> +    function void add_traffic_shaping(input int unsigned len, input int unsigned size, input int unsigned freq);
@micprog I added a second function (`add_traffic_shaping_with_size`) and reverted the changes to `add_traffic_shaping` to avoid changing the interface. Let me know if that works for you. Thanks!

2024-05-08 07:47 UTC, micprog approved these changes
LGTM :+1:

2024-05-08 14:22 UTC, merged